accessing
communicationError: anError
	^self at:'error' put: anError.
	
